function model=initModel_yeast()

model.description='M-Model';
model.id='Yeast76';
model.rxns={};
model.mets={};
model.S=0;
model.lb=0;
model.ub=0;
model.rev=0;
model.c=0;
model.b=0;
model.comps={'cell envelope';'cytoplasm';'endoplasmic reticulum';'endoplasmic reticulum membrane';'extracellular';'Golgi';'Golgi membrane';'lipid particle';'mitochondrial membrane';'mitochondrion';'nucleus';'peroxisomal membrane';'peroxisome';'vacuolar membrane';'vacuole'};
model.compNames={'cell envelope';'cytoplasm';'endoplasmic reticulum';'endoplasmic reticulum membrane';'extracellular';'Golgi';'Golgi membrane';'lipid particle';'mitochondrial membrane';'mitochondrion';'nucleus';'peroxisomal membrane';'peroxisome';'vacuolar membrane';'vacuole'};
model.compOutside={'cell envelope';'cytoplasm';'endoplasmic reticulum';'endoplasmic reticulum membrane';'extracellular';'Golgi';'Golgi membrane';'lipid particle';'mitochondrial membrane';'mitochondrion';'nucleus';'peroxisomal membrane';'peroxisome';'vacuolar membrane';'vacuole'};
model.rxnNames={};
model.metNames={};
model.metComps={};
model.rxnGeneMat=0;
model.genes={};
model.grRules={};
model.metFormulas={};
model.subSystems={};
model.unconstrained=0;
model.eccodes={};
model.unconstrained=true;
model.metFormulas={};
model.inchis={};
model.metMiriams={};
model.first=1;

